fedora:
  Native:
    - btop
  Flatpaks:
    - com.github.dail8859.NotepadNext
    - io.github.nuttyartist.notes
  Local:
    - /home/user/Downloads/custom-app.rpm

ubuntu:
  Native:
    - btop
  Flatpaks:
    - com.github.dail8859.NotepadNext
    - io.github.nuttyartist.notes
  Local:
    - /home/user/Downloads/custom-app.dpkg
  
any:
  Flatpaks:
    - com.github.dail8859.NotepadNext
    - io.github.nuttyartist.notes
  Local:
    - /home/user/Downloads/custom-app.rpm